baseURL                    = 'https://example.org/'
languageCode               = 'en-us'
title                      = 'Threathunters.io'

# Language settings
contentDir                 = "content/en"
defaultContentLanguage     = "en"

# hugo module configuration

[module]
  # Uncomment the next line to build and serve using local docsy clone declared in the named Hugo workspace:
  # workspace = "docsy.work"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

[params]
  # Google Custom Search Engine ID. Remove or comment out to disable search.
  # gcs_engine_id = "011737558837375720776:fsdu1nryfng"
  offlineSearch = true
  [params.ui]
    showLightDarkModeMenu = true
    navbar_logo = true
    sidebar_search_disable = false
    sidebar_menu_compact = true
    ul_show = 1
    sidebar_menu_foldable = true
    sidebar_cache_limit = 1000
    navbar_translucent_over_cover_disable = true
  [params.copyright]
    authors = "Threathunters.io Authors. All rights reserved."
    # from_year = 2024

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"


